package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoAluno;
import fatec.poo.model.Aluno;
import fatec.poo.model.Pessoa;
import static fatec.poo.model.Pessoa.validadarCPF;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme Sernajoto
 * @author Bárbara Sajo
 */
public class GuiAluno extends javax.swing.JFrame {

    /**
     * Creates new form GuiCurso
     */
    public GuiAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnInserir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnConsultar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();
        jLblCPF = new javax.swing.JLabel();
        jFrmtdTxtFCPF = new javax.swing.JFormattedTextField();
        jLblNome = new javax.swing.JLabel();
        jTxtFNome = new javax.swing.JTextField();
        jLblSexo = new javax.swing.JLabel();
        jCbBxSexo = new javax.swing.JComboBox<>();
        jLblEstadoCivil = new javax.swing.JLabel();
        jCbBxEstadoCivil = new javax.swing.JComboBox<>();
        jLblEscolaridade = new javax.swing.JLabel();
        jCbBxEscolaridade = new javax.swing.JComboBox<>();
        jLblEndereco = new javax.swing.JLabel();
        jTxtFBairro = new javax.swing.JTextField();
        jLblBairro = new javax.swing.JLabel();
        jTxtFEnder = new javax.swing.JTextField();
        jLblCidade = new javax.swing.JLabel();
        jTxtFCidade = new javax.swing.JTextField();
        jLblRG = new javax.swing.JLabel();
        jLblEmail = new javax.swing.JLabel();
        jTxtFEmail = new javax.swing.JTextField();
        jLblNoEndereco = new javax.swing.JLabel();
        jTxtFNum = new javax.swing.JTextField();
        jLblCEP = new javax.swing.JLabel();
        jLblEstado = new javax.swing.JLabel();
        jCbBxEstado = new javax.swing.JComboBox<>();
        jLblTelRes = new javax.swing.JLabel();
        jLblCelular = new javax.swing.JLabel();
        jFrmtdTxtFCEP = new javax.swing.JFormattedTextField();
        jFrmtdTxtFTelRes = new javax.swing.JFormattedTextField();
        jFrmtdTxtFCel = new javax.swing.JFormattedTextField();
        jFrmtdTxtFRG = new javax.swing.JFormattedTextField();
        jLblDataNascto = new javax.swing.JLabel();
        jFrmtdTxtFDataNascto = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Aluno");
        setPreferredSize(new java.awt.Dimension(650, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jBtnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        jBtnInserir.setText("Inserir");
        jBtnInserir.setEnabled(false);
        jBtnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInserirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.setEnabled(false);
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setEnabled(false);
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });

        jLblCPF.setText("CPF");

        try {
            jFrmtdTxtFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFrmtdTxtFCPFActionPerformed(evt);
            }
        });

        jLblNome.setText("Nome");

        jTxtFNome.setEnabled(false);

        jLblSexo.setText("Sexo");

        jCbBxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jCbBxSexo.setEnabled(false);

        jLblEstadoCivil.setText("Estado Civil");

        jCbBxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado", "Solteiro" }));
        jCbBxEstadoCivil.setEnabled(false);

        jLblEscolaridade.setText("Escolaridade");

        jCbBxEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensino Fundamental", "Ensino Médio", "Ensino Superior" }));
        jCbBxEscolaridade.setEnabled(false);

        jLblEndereco.setText("Endereço");

        jTxtFBairro.setEnabled(false);

        jLblBairro.setText("Bairro");

        jTxtFEnder.setEnabled(false);

        jLblCidade.setText("Cidade");

        jTxtFCidade.setEnabled(false);

        jLblRG.setText("RG");

        jLblEmail.setText("Email");

        jTxtFEmail.setEnabled(false);

        jLblNoEndereco.setText("Nº");

        jTxtFNum.setEnabled(false);

        jLblCEP.setText("CEP");

        jLblEstado.setText("Estado");

        jCbBxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jCbBxEstado.setEnabled(false);

        jLblTelRes.setText("Tel. Res");

        jLblCelular.setText("Celular");

        try {
            jFrmtdTxtFCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFCEP.setEnabled(false);

        try {
            jFrmtdTxtFTelRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFTelRes.setEnabled(false);

        try {
            jFrmtdTxtFCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFCel.setEnabled(false);

        try {
            jFrmtdTxtFRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFRG.setEnabled(false);

        jLblDataNascto.setText("Data Nascto.");

        try {
            jFrmtdTxtFDataNascto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFDataNascto.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblCPF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblSexo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblEndereco, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblBairro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblCidade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblRG, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLblEstado))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(jLblDataNascto))
                                    .addComponent(jTxtFEnder, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFrmtdTxtFDataNascto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jFrmtdTxtFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCbBxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLblEstadoCivil)
                                .addGap(18, 18, 18)
                                .addComponent(jCbBxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLblEscolaridade)
                                .addGap(18, 18, 18)
                                .addComponent(jCbBxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(383, 383, 383)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLblNoEndereco)
                                                .addComponent(jLblCEP))
                                            .addGap(24, 24, 24))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLblCelular)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jCbBxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(49, 49, 49)
                                                    .addComponent(jLblTelRes)))
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFrmtdTxtFRG, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(293, 293, 293)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFrmtdTxtFTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFrmtdTxtFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFNum, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFrmtdTxtFCel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jBtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCPF)
                    .addComponent(jFrmtdTxtFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNome)
                    .addComponent(jTxtFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblDataNascto)
                    .addComponent(jFrmtdTxtFDataNascto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblSexo)
                    .addComponent(jCbBxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblEstadoCivil)
                    .addComponent(jCbBxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblEscolaridade)
                    .addComponent(jCbBxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEndereco)
                    .addComponent(jTxtFEnder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNoEndereco)
                    .addComponent(jTxtFNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblBairro)
                    .addComponent(jLblCEP)
                    .addComponent(jFrmtdTxtFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCidade)
                    .addComponent(jTxtFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblEstado)
                    .addComponent(jCbBxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTelRes)
                    .addComponent(jFrmtdTxtFTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblRG)
                    .addComponent(jLblCelular)
                    .addComponent(jFrmtdTxtFCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFrmtdTxtFRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEmail)
                    .addComponent(jTxtFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnConsultar)
                    .addComponent(jBtnInserir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Cadastar Aluno");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        aluno = null;
        aluno = daoAluno.consultar(jFrmtdTxtFCPF.getText().replaceAll("[.,-]", ""));
        
        if(Pessoa.validadarCPF(jFrmtdTxtFCPF.getText().replaceAll("[.,-]", "")) == true){
            if(aluno == null){
                jFrmtdTxtFCPF.setEnabled(false);
                jTxtFNome.setEnabled(true);
                jTxtFNome.requestFocus();
                jFrmtdTxtFDataNascto.setEnabled(true);
                jCbBxSexo.setEnabled(true);
                jCbBxEstadoCivil.setEnabled(true);
                jCbBxEscolaridade.setEnabled(true);
                jTxtFEnder.setEnabled(true);
                jTxtFNum.setEnabled(true);
                jTxtFBairro.setEnabled(true);
                jFrmtdTxtFCEP.setEnabled(true);
                jTxtFCidade.setEnabled(true);
                jCbBxEstado.setEnabled(true);
                jFrmtdTxtFTelRes.setEnabled(true);
                jFrmtdTxtFRG.setEnabled(true);
                jFrmtdTxtFCel.setEnabled(true);
                jTxtFEmail.setEnabled(true);

                jBtnConsultar.setEnabled(false);
                jBtnInserir.setEnabled(true);
                jBtnAlterar.setEnabled(false);
                jBtnExcluir.setEnabled(false);   
            }else{
                jTxtFNome.setText(aluno.getNome());
                jFrmtdTxtFDataNascto.setText(aluno.getDataNasc());
                jCbBxSexo.setSelectedItem(aluno.getSexo());
                jCbBxEstadoCivil.setSelectedItem(aluno.getEstadoCivil());
                jCbBxEscolaridade.setSelectedItem(aluno.getEscolaridade());
                jTxtFEnder.setText(aluno.getEndereco());
                jTxtFNum.setText(Integer.toString(aluno.getNumero()));
                jTxtFBairro.setText(aluno.getBairro());
                jFrmtdTxtFCEP.setText(aluno.getCpf());
                jTxtFCidade.setText(aluno.getCidade());
                jCbBxEstado.setSelectedItem(aluno.getEstado());
                jFrmtdTxtFTelRes.setText(aluno.getTelefone());
                jFrmtdTxtFRG.setText(aluno.getRg());
                jFrmtdTxtFCel.setText(aluno.getCelular());
                jTxtFEmail.setText(aluno.getEmail());
                
                jFrmtdTxtFCPF.setEnabled(false);
                jTxtFNome.setEnabled(true);
                jTxtFNome.requestFocus();
                jFrmtdTxtFDataNascto.setEnabled(true);
                jCbBxSexo.setEnabled(true);
                jCbBxEstadoCivil.setEnabled(true);
                jCbBxEscolaridade.setEnabled(true);
                jTxtFEnder.setEnabled(true);
                jTxtFNum.setEnabled(true);
                jTxtFBairro.setEnabled(true);
                jFrmtdTxtFCEP.setEnabled(true);
                jTxtFCidade.setEnabled(true);
                jCbBxEstado.setEnabled(true);
                jFrmtdTxtFTelRes.setEnabled(true);
                jFrmtdTxtFRG.setEnabled(true);
                jFrmtdTxtFCel.setEnabled(true);
                jTxtFEmail.setEnabled(true);

                jBtnConsultar.setEnabled(false);
                jBtnInserir.setEnabled(false);
                jBtnAlterar.setEnabled(true);
                jBtnExcluir.setEnabled(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "CPF Inválido");
        }
    }//GEN-LAST:event_jBtnConsultarActionPerformed

    private void jFrmtdTxtFCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFrmtdTxtFCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrmtdTxtFCPFActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("poo", "batata123");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        daoAluno = new DaoAluno(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void jBtnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInserirActionPerformed
        daoAluno = new DaoAluno(conexao.conectar());
        
        aluno = new Aluno(jTxtFNome.getText(), jFrmtdTxtFCPF.getText().replaceAll("[.,-]", ""));
        aluno.setDataNasc(jFrmtdTxtFDataNascto.getText());
        aluno.setSexo(jCbBxSexo.getSelectedItem().toString());
        aluno.setEstadoCivil(jCbBxEstadoCivil.getSelectedItem().toString());
        aluno.setEscolaridade(jCbBxEscolaridade.getSelectedItem().toString());
        aluno.setEndereco(jTxtFEnder.getText());
        aluno.setNumero(Integer.parseInt(jTxtFNum.getText()));
        aluno.setBairro(jTxtFBairro.getText());
        aluno.setCep(jFrmtdTxtFCEP.getText().replaceAll("[.,-]", ""));
        aluno.setCidade(jTxtFCidade.getText());
        aluno.setEstado(jCbBxEstado.getSelectedItem().toString());
        aluno.setTelefone(jFrmtdTxtFTelRes.getText().replaceAll("[),(,.,-]", ""));
        aluno.setRg(jFrmtdTxtFRG.getText().replaceAll("[.,-]", ""));
        aluno.setCelular(jFrmtdTxtFCel.getText().replaceAll("[),(,.,-]", ""));
        aluno.setEmail(jTxtFEmail.getText());
        
        daoAluno.inserir(aluno);
        
        jFrmtdTxtFCPF.setText("");
        jTxtFNome.setText("");
        jFrmtdTxtFDataNascto.setText("");
        jTxtFEnder.setText("");
        jTxtFNum.setText("");
        jTxtFBairro.setText("");
        jFrmtdTxtFCEP.setText("");
        jTxtFCidade.setText("");
        jFrmtdTxtFTelRes.setText("");
        jFrmtdTxtFRG.setText("");
        jFrmtdTxtFCel.setText("");
        jTxtFEmail.setText("");
        
        jFrmtdTxtFCPF.setEnabled(true);
        jFrmtdTxtFCPF.requestFocus();
        jTxtFNome.setEnabled(false);
        jFrmtdTxtFDataNascto.setEnabled(false);
        jCbBxSexo.setEnabled(false);
        jCbBxEstadoCivil.setEnabled(false);
        jCbBxEscolaridade.setEnabled(false);
        jTxtFEnder.setEnabled(false);
        jTxtFNum.setEnabled(false);
        jTxtFBairro.setEnabled(false);
        jFrmtdTxtFCEP.setEnabled(false);
        jTxtFCidade.setEnabled(false);
        jCbBxEstado.setEnabled(false);
        jFrmtdTxtFTelRes.setEnabled(false);
        jFrmtdTxtFRG.setEnabled(false);
        jFrmtdTxtFCel.setEnabled(false);
        jTxtFEmail.setEnabled(false);

        jBtnConsultar.setEnabled(true);
        jBtnInserir.setEnabled(false);
    }//GEN-LAST:event_jBtnInserirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0){
            aluno.setNome(jTxtFNome.getText());
            aluno.setDataNasc(jFrmtdTxtFDataNascto.getText());
            aluno.setSexo(jCbBxSexo.getSelectedItem().toString());
            aluno.setEstadoCivil(jCbBxEstadoCivil.getSelectedItem().toString());
            aluno.setEscolaridade(jCbBxEscolaridade.getSelectedItem().toString());
            aluno.setEndereco(jTxtFEnder.getText());
            aluno.setNumero(Integer.parseInt(jTxtFNum.getText()));
            aluno.setBairro(jTxtFBairro.getText());
            aluno.setCep(jFrmtdTxtFCEP.getText().replaceAll("[.,-]", ""));
            aluno.setCidade(jTxtFCidade.getText());
            aluno.setEstado(jCbBxEstado.getSelectedItem().toString());
            aluno.setTelefone(jFrmtdTxtFTelRes.getText().replaceAll("[),(,.,-]", ""));
            aluno.setRg(jFrmtdTxtFRG.getText().replaceAll("[.,-]", ""));
            aluno.setCelular(jFrmtdTxtFCel.getText().replaceAll("[),(,.,-]", ""));
            aluno.setEmail(jTxtFEmail.getText());
           
           daoAluno.alterar(aluno);
        }
        
        jFrmtdTxtFCPF.setText("");
        jTxtFNome.setText("");
        jFrmtdTxtFDataNascto.setText("");
        jTxtFEnder.setText("");
        jTxtFNum.setText("");
        jTxtFBairro.setText("");
        jFrmtdTxtFCEP.setText("");
        jTxtFCidade.setText("");
        jFrmtdTxtFTelRes.setText("");
        jFrmtdTxtFRG.setText("");
        jFrmtdTxtFCel.setText("");
        jTxtFEmail.setText("");
        
        jFrmtdTxtFCPF.setEnabled(true);
        jFrmtdTxtFCPF.requestFocus();
        jTxtFNome.setEnabled(false);
        jFrmtdTxtFDataNascto.setEnabled(false);
        jCbBxSexo.setEnabled(false);
        jCbBxEstadoCivil.setEnabled(false);
        jCbBxEscolaridade.setEnabled(false);
        jTxtFEnder.setEnabled(false);
        jTxtFNum.setEnabled(false);
        jTxtFBairro.setEnabled(false);
        jFrmtdTxtFCEP.setEnabled(false);
        jTxtFCidade.setEnabled(false);
        jCbBxEstado.setEnabled(false);
        jFrmtdTxtFTelRes.setEnabled(false);
        jFrmtdTxtFRG.setEnabled(false);
        jFrmtdTxtFCel.setEnabled(false);
        jTxtFEmail.setEnabled(false);
        
        jBtnConsultar.setEnabled(true);
        jBtnInserir.setEnabled(false);
        jBtnAlterar.setEnabled(false);
        jBtnExcluir.setEnabled(false);   
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
         if (JOptionPane.showConfirmDialog(null, "Confirma Exclsão?") == 0){
            daoAluno.excluir(aluno);
            
            jFrmtdTxtFCPF.setText("");
            jTxtFNome.setText("");
            jFrmtdTxtFDataNascto.setText("");
            jTxtFEnder.setText("");
            jTxtFNum.setText("");
            jTxtFBairro.setText("");
            jFrmtdTxtFCEP.setText("");
            jTxtFCidade.setText("");
            jFrmtdTxtFTelRes.setText("");
            jFrmtdTxtFRG.setText("");
            jFrmtdTxtFCel.setText("");
            jTxtFEmail.setText("");

            jFrmtdTxtFCPF.setEnabled(true);
            jFrmtdTxtFCPF.requestFocus();
            jTxtFNome.setEnabled(false);
            jFrmtdTxtFDataNascto.setEnabled(false);
            jCbBxSexo.setEnabled(false);
            jCbBxEstadoCivil.setEnabled(false);
            jCbBxEscolaridade.setEnabled(false);
            jTxtFEnder.setEnabled(false);
            jTxtFNum.setEnabled(false);
            jTxtFBairro.setEnabled(false);
            jFrmtdTxtFCEP.setEnabled(false);
            jTxtFCidade.setEnabled(false);
            jCbBxEstado.setEnabled(false);
            jFrmtdTxtFTelRes.setEnabled(false);
            jFrmtdTxtFRG.setEnabled(false);
            jFrmtdTxtFCel.setEnabled(false);
            jTxtFEmail.setEnabled(false);

            jBtnConsultar.setEnabled(true);
            jBtnInserir.setEnabled(false);
            jBtnAlterar.setEnabled(false);
            jBtnExcluir.setEnabled(false);
        } 
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnInserir;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JComboBox<String> jCbBxEscolaridade;
    private javax.swing.JComboBox<String> jCbBxEstado;
    private javax.swing.JComboBox<String> jCbBxEstadoCivil;
    private javax.swing.JComboBox<String> jCbBxSexo;
    private javax.swing.JFormattedTextField jFrmtdTxtFCEP;
    private javax.swing.JFormattedTextField jFrmtdTxtFCPF;
    private javax.swing.JFormattedTextField jFrmtdTxtFCel;
    private javax.swing.JFormattedTextField jFrmtdTxtFDataNascto;
    private javax.swing.JFormattedTextField jFrmtdTxtFRG;
    private javax.swing.JFormattedTextField jFrmtdTxtFTelRes;
    private javax.swing.JLabel jLblBairro;
    private javax.swing.JLabel jLblCEP;
    private javax.swing.JLabel jLblCPF;
    private javax.swing.JLabel jLblCelular;
    private javax.swing.JLabel jLblCidade;
    private javax.swing.JLabel jLblDataNascto;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblEndereco;
    private javax.swing.JLabel jLblEscolaridade;
    private javax.swing.JLabel jLblEstado;
    private javax.swing.JLabel jLblEstadoCivil;
    private javax.swing.JLabel jLblNoEndereco;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblRG;
    private javax.swing.JLabel jLblSexo;
    private javax.swing.JLabel jLblTelRes;
    private javax.swing.JTextField jTxtFBairro;
    private javax.swing.JTextField jTxtFCidade;
    private javax.swing.JTextField jTxtFEmail;
    private javax.swing.JTextField jTxtFEnder;
    private javax.swing.JTextField jTxtFNome;
    private javax.swing.JTextField jTxtFNum;
    // End of variables declaration//GEN-END:variables
    private DaoAluno daoAluno = null;
    private Aluno aluno = null;
    private Conexao conexao = null;
    private Pessoa pessoa = null;
}
