package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoAPrazo;
import fatec.poo.control.DaoAVista;
import fatec.poo.control.DaoAluno;
import fatec.poo.control.DaoCurso;
import fatec.poo.control.DaoMatricula;
import fatec.poo.control.DaoTurma;
import fatec.poo.model.APrazo;
import fatec.poo.model.AVista;
import fatec.poo.model.Aluno;
import fatec.poo.model.Curso;
import fatec.poo.model.Matricula;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Turma;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme Sernajoto
 * @author André Constancio
 */
public class GuiEfetuarMatricula extends javax.swing.JFrame {

    /**
     * Creates new form GuiEfetuarMatricula
     */
    public GuiEfetuarMatricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fprBtnPagamento = new javax.swing.ButtonGroup();
        jBtnInserir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnConsultar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();
        jLblDataMatricula = new javax.swing.JLabel();
        jFrmtdTxtFDataMatricula = new javax.swing.JFormattedTextField();
        jLblCurso = new javax.swing.JLabel();
        jCbBxCurso = new javax.swing.JComboBox<>();
        jCbBxTurma = new javax.swing.JComboBox<>();
        jLblTurma = new javax.swing.JLabel();
        jLblCPF = new javax.swing.JLabel();
        jFrmtdTxtFCPF = new javax.swing.JFormattedTextField();
        jLblValor = new javax.swing.JLabel();
        jTxtFValor = new javax.swing.JTextField();
        jTxtFNome = new javax.swing.JTextField();
        jLblNome = new javax.swing.JLabel();
        jPnlPagamento = new javax.swing.JPanel();
        jRadBtnAVista = new javax.swing.JRadioButton();
        jRadBtnParcelado = new javax.swing.JRadioButton();
        jLblDataVencimento = new javax.swing.JLabel();
        jFrmtdTxtFDataVencimento = new javax.swing.JFormattedTextField();
        jFrmtdTxtFDataPagamento = new javax.swing.JFormattedTextField();
        jLblDataPagamento = new javax.swing.JLabel();
        jTxtFAgencia = new javax.swing.JTextField();
        jLblAgencia = new javax.swing.JLabel();
        jTxtFQtdeMensalidades = new javax.swing.JTextField();
        jLblQtdeMensalidades = new javax.swing.JLabel();
        jLblNumCheque = new javax.swing.JLabel();
        jTxtFNumCheque = new javax.swing.JTextField();
        jLblTaxaJuros = new javax.swing.JLabel();
        jTxtFTaxaJuros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Efetuar Matrícula");
        setPreferredSize(new java.awt.Dimension(650, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jBtnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        jBtnInserir.setText("Inserir");
        jBtnInserir.setEnabled(false);
        jBtnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInserirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.setEnabled(false);
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setEnabled(false);
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });

        jLblDataMatricula.setText("Data Matrícula");

        try {
            jFrmtdTxtFDataMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLblCurso.setText("Curso");

        jCbBxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbBxCursoActionPerformed(evt);
            }
        });

        jCbBxTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbBxTurmaActionPerformed(evt);
            }
        });

        jLblTurma.setText("Turma");

        jLblCPF.setText("CPF Aluno");

        try {
            jFrmtdTxtFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFCPF.setEnabled(false);

        jLblValor.setText("Valor R$");

        jTxtFValor.setEditable(false);

        jTxtFNome.setEditable(false);

        jLblNome.setText("Nome");

        jPnlPagamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));

        fprBtnPagamento.add(jRadBtnAVista);
        jRadBtnAVista.setText("À Vista");
        jRadBtnAVista.setEnabled(false);
        jRadBtnAVista.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadBtnAVistaStateChanged(evt);
            }
        });

        fprBtnPagamento.add(jRadBtnParcelado);
        jRadBtnParcelado.setText("Parcelado");
        jRadBtnParcelado.setEnabled(false);
        jRadBtnParcelado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadBtnParceladoStateChanged(evt);
            }
        });

        jLblDataVencimento.setText("Data 1º Vencto.");

        try {
            jFrmtdTxtFDataVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFDataVencimento.setEnabled(false);

        try {
            jFrmtdTxtFDataPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFDataPagamento.setEnabled(false);

        jLblDataPagamento.setText("Data Pagto.");

        jTxtFAgencia.setEnabled(false);

        jLblAgencia.setText("Agência");

        jTxtFQtdeMensalidades.setEnabled(false);

        jLblQtdeMensalidades.setText("Qtde. Mensalidades");

        jLblNumCheque.setText("No. Cheque");

        jTxtFNumCheque.setEnabled(false);

        jLblTaxaJuros.setText("Tx. Juros(%)");

        jTxtFTaxaJuros.setEnabled(false);

        javax.swing.GroupLayout jPnlPagamentoLayout = new javax.swing.GroupLayout(jPnlPagamento);
        jPnlPagamento.setLayout(jPnlPagamentoLayout);
        jPnlPagamentoLayout.setHorizontalGroup(
            jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadBtnAVista)
                    .addComponent(jRadBtnParcelado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblAgencia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblQtdeMensalidades, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtFAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFQtdeMensalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblNumCheque)
                    .addComponent(jLblTaxaJuros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtFNumCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblDataPagamento)
                    .addComponent(jLblDataVencimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFrmtdTxtFDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFrmtdTxtFDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPnlPagamentoLayout.setVerticalGroup(
            jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPagamentoLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jFrmtdTxtFDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFNumCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNumCheque)
                    .addComponent(jTxtFAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblAgencia)
                    .addComponent(jRadBtnAVista))
                .addGap(30, 30, 30)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRadBtnParcelado)
                    .addComponent(jLblQtdeMensalidades)
                    .addComponent(jTxtFQtdeMensalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblDataVencimento)
                    .addComponent(jFrmtdTxtFDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblTurma)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblCPF)
                                .addComponent(jLblDataMatricula)
                                .addComponent(jLblCurso)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCbBxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCbBxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFrmtdTxtFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLblNome)
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLblValor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtFValor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jFrmtdTxtFDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jBtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDataMatricula)
                    .addComponent(jFrmtdTxtFDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCbBxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCurso)
                    .addComponent(jLblValor)
                    .addComponent(jTxtFValor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbBxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTurma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLblCPF)
                    .addComponent(jFrmtdTxtFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblNome)
                        .addComponent(jTxtFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnlPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnSair)
                    .addComponent(jBtnInserir)
                    .addComponent(jBtnConsultar))
                .addGap(118, 118, 118))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInserirActionPerformed
        avista = null;
        aprazo = null;
        turma = daoTurma.consultar(jCbBxTurma.getSelectedItem().toString());

        if (jRadBtnAVista.isSelected()) {
            avista = new AVista();
            avista.setValor(Double.parseDouble(jTxtFValor.getText()));
            avista.setAgencia(Integer.parseInt(jTxtFAgencia.getText()));
            avista.setPreData(jFrmtdTxtFDataPagamento.getText());
            avista.setnCheque(Integer.parseInt(jTxtFNumCheque.getText()));
            daoAVista.inserir(avista);
        } else {
            aprazo = new APrazo();
            aprazo.setValor(Double.parseDouble(jTxtFValor.getText()));
            aprazo.setQtdeMensalidade(Integer.parseInt(jTxtFQtdeMensalidades.getText()));
            aprazo.setTaxaJuros(Double.parseDouble(jTxtFTaxaJuros.getText()));
            aprazo.setDtVencimento(jFrmtdTxtFDataVencimento.getText());
            daoAPrazo.inserir(aprazo);
        }
        matricula = new Matricula(jFrmtdTxtFDataMatricula.getText());
        matricula.setAluno(daoAluno.consultar(jFrmtdTxtFCPF.getText().replaceAll("[.,-]", "")));
        matricula.setaPrazo(aprazo);
        matricula.setaVista(avista);
        turma.addMatricula(matricula);
        daoMatricula.inserir(matricula);

        jBtnConsultar.setEnabled(true);
        jBtnAlterar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        jBtnInserir.setEnabled(false);
        jCbBxCurso.setEnabled(true);
        jCbBxTurma.setEnabled(true);
        jCbBxCurso.setSelectedIndex(0);
        jFrmtdTxtFDataMatricula.setText("");
        jFrmtdTxtFDataMatricula.setEnabled(true);
        jFrmtdTxtFDataMatricula.requestFocus();
        jTxtFNome.setText("");
        jFrmtdTxtFCPF.setText("");
        jFrmtdTxtFCPF.setEnabled(false);
        
        
        jRadBtnAVista.setSelected(false);
        jRadBtnAVista.setEnabled(false);
        jTxtFAgencia.setEnabled(false);
        jTxtFAgencia.setText("");
        jTxtFNumCheque.setEnabled(false);
        jTxtFNumCheque.setText("");
        jFrmtdTxtFDataPagamento.setEnabled(false);
        jFrmtdTxtFDataPagamento.setText("");
        
        jRadBtnParcelado.setSelected(false);
        jRadBtnParcelado.setEnabled(false);
        jTxtFQtdeMensalidades.setEnabled(false);
        jTxtFQtdeMensalidades.setText("");
        jTxtFTaxaJuros.setEnabled(false);
        jTxtFTaxaJuros.setText("");
        jFrmtdTxtFDataVencimento.setEnabled(false);
        jFrmtdTxtFDataVencimento.setText("");
        
    }//GEN-LAST:event_jBtnInserirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0) {
            if (jRadBtnAVista.isSelected()) {
                if (matricula.getaVista() == null) {
                    avista = new AVista();
                    avista.setValor(Double.parseDouble(jTxtFValor.getText()));
                    avista.setAgencia(Integer.parseInt(jTxtFAgencia.getText()));
                    avista.setPreData(jFrmtdTxtFDataPagamento.getText());
                    avista.setnCheque(Integer.parseInt(jTxtFNumCheque.getText()));
                    
                    daoAVista.inserir(avista);
                    matricula.setaVista(avista);
                    aprazo = matricula.getaPrazo();
                    matricula.setaPrazo(null);
                    daoMatricula.alterar(matricula);
                    daoAPrazo.excluir(aprazo);
                } else {
                    matricula.getaVista().setAgencia(Integer.parseInt(jTxtFAgencia.getText()));
                    matricula.getaVista().setPreData(jFrmtdTxtFDataPagamento.getText());
                    matricula.getaVista().setnCheque(Integer.parseInt(jTxtFNumCheque.getText()));
                    daoAVista.alterar(matricula.getaVista());
                    daoMatricula.alterar(matricula);
                }
            } else {
                if (matricula.getaPrazo() == null) {
                    aprazo = new APrazo();
                    aprazo.setValor(Double.parseDouble(jTxtFValor.getText()));
                    aprazo.setQtdeMensalidade(Integer.parseInt(jTxtFQtdeMensalidades.getText()));
                    aprazo.setTaxaJuros(Double.parseDouble(jTxtFTaxaJuros.getText()));
                    aprazo.setDtVencimento(jFrmtdTxtFDataVencimento.getText());
                    
                    daoAPrazo.inserir(aprazo);
                    matricula.setaPrazo(aprazo);
                    avista = matricula.getaVista();
                    matricula.setaVista(null);
                    daoMatricula.alterar(matricula);
                    daoAVista.excluir(avista);
                } else {
                    matricula.getaPrazo().setQtdeMensalidade(Integer.parseInt(jTxtFQtdeMensalidades.getText()));
                    matricula.getaPrazo().setTaxaJuros(Double.parseDouble(jTxtFTaxaJuros.getText()));
                    matricula.getaPrazo().setDtVencimento(jFrmtdTxtFDataVencimento.getText());
                    daoAPrazo.alterar(matricula.getaPrazo());
                    daoMatricula.alterar(matricula);
                }                
            }
        }
jBtnConsultar.setEnabled(true);
        jBtnAlterar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        jBtnInserir.setEnabled(false);
        jCbBxCurso.setEnabled(true);
        jCbBxTurma.setEnabled(true);
        jCbBxCurso.setSelectedIndex(0);
        jFrmtdTxtFDataMatricula.setText("");
        jFrmtdTxtFDataMatricula.setEnabled(true);
        jFrmtdTxtFDataMatricula.requestFocus();
        jTxtFNome.setText("");
        jFrmtdTxtFCPF.setText("");
        jFrmtdTxtFCPF.setEnabled(false);
        
        
        jRadBtnAVista.setSelected(false);
        jRadBtnAVista.setEnabled(false);
        jTxtFAgencia.setEnabled(false);
        jTxtFAgencia.setText("");
        jTxtFNumCheque.setEnabled(false);
        jTxtFNumCheque.setText("");
        jFrmtdTxtFDataPagamento.setEnabled(false);
        jFrmtdTxtFDataPagamento.setText("");
        
        jRadBtnParcelado.setSelected(false);
        jRadBtnParcelado.setEnabled(false);
        jTxtFQtdeMensalidades.setEnabled(false);
        jTxtFQtdeMensalidades.setText("");
        jTxtFTaxaJuros.setEnabled(false);
        jTxtFTaxaJuros.setText("");
        jFrmtdTxtFDataVencimento.setEnabled(false);
        jFrmtdTxtFDataVencimento.setText("");
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
        aluno = null;
        matricula = null;

        if (Pessoa.validarCPF(jFrmtdTxtFCPF.getText().replaceAll("[.,-]", ""))) {
            matricula = daoMatricula.consultar(jFrmtdTxtFCPF.getText().replaceAll("[.,-]", ""));
            aluno = daoAluno.consultar(jFrmtdTxtFCPF.getText().replaceAll("[.,-]", ""));
            if (aluno != null) {
                jTxtFNome.setText(aluno.getNome());
                jFrmtdTxtFCPF.setEnabled(false);
                jCbBxCurso.setEnabled(false);
                jCbBxTurma.setEnabled(false);
                jBtnConsultar.setEnabled(false);
                if (matricula == null) {
                    jBtnAlterar.setEnabled(false);
                    jBtnExcluir.setEnabled(false);
                    jBtnInserir.setEnabled(true);
                } else {
                    jBtnAlterar.setEnabled(true);
                    jBtnExcluir.setEnabled(true);
                    jBtnInserir.setEnabled(false);
                    jFrmtdTxtFDataMatricula.setText(matricula.getData());
                    jFrmtdTxtFDataMatricula.setEnabled(false);

                    turma = daoTurma.consultar(matricula.getTurma().getSiglaTurma());
                    curso = daoCurso.consultar(turma.getCurso().getSigla());
                    jCbBxCurso.setSelectedItem(curso.getSigla());
                    jCbBxTurma.setSelectedItem(turma.getSiglaTurma());

                    if (matricula.getaVista() == null) {
                        jRadBtnParcelado.setSelected(true);
                        jTxtFQtdeMensalidades.setText(String.valueOf(matricula.getaPrazo().getQtdeMensalidade()));
                        jTxtFTaxaJuros.setText(String.valueOf(matricula.getaPrazo().getTaxaJuros()));
                        jFrmtdTxtFDataVencimento.setText(matricula.getaPrazo().getDtVencimento());
                    } else {
                        jRadBtnAVista.setSelected(true);
                        jTxtFAgencia.setText(String.valueOf(matricula.getaVista().getAgencia()));
                        jTxtFNumCheque.setText(String.valueOf(matricula.getaVista().getnCheque()));
                        jFrmtdTxtFDataPagamento.setText(matricula.getaVista().getPreData());
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Aluno não cadastrado.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF Inválido");
        }
    }//GEN-LAST:event_jBtnConsultarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclsão?") == 0) {
            daoMatricula.excluir(matricula);
            matricula.getAluno().setMatricula(null);
            matricula.getTurma().remMatricula(matricula);
            matricula.setaPrazo(null);
            matricula.setaVista(null);
            
            jBtnConsultar.setEnabled(true);
            jBtnAlterar.setEnabled(false);
            jBtnExcluir.setEnabled(false);
            jBtnInserir.setEnabled(false);
            jCbBxCurso.setEnabled(true);
            jCbBxTurma.setEnabled(true);
            jCbBxCurso.setSelectedIndex(0);
            jFrmtdTxtFDataMatricula.setText("");
            jFrmtdTxtFDataMatricula.setEnabled(true);
            jFrmtdTxtFDataMatricula.requestFocus();
            jTxtFNome.setText("");
            jFrmtdTxtFCPF.setText("");
            jFrmtdTxtFCPF.setEnabled(false);


            jRadBtnAVista.setSelected(false);
            jRadBtnAVista.setEnabled(false);
            jTxtFAgencia.setEnabled(false);
            jTxtFAgencia.setText("");
            jTxtFNumCheque.setEnabled(false);
            jTxtFNumCheque.setText("");
            jFrmtdTxtFDataPagamento.setEnabled(false);
            jFrmtdTxtFDataPagamento.setText("");

            jRadBtnParcelado.setSelected(false);
            jRadBtnParcelado.setEnabled(false);
            jTxtFQtdeMensalidades.setEnabled(false);
            jTxtFQtdeMensalidades.setText("");
            jTxtFTaxaJuros.setEnabled(false);
            jTxtFTaxaJuros.setText("");
            jFrmtdTxtFDataVencimento.setEnabled(false);
            jFrmtdTxtFDataVencimento.setText("");
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("BD1711035", "BD1711035");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@apolo:1521:xe");
        daoCurso = new DaoCurso(conexao.conectar());
        daoMatricula = new DaoMatricula(conexao.conectar());
        daoTurma = new DaoTurma(conexao.conectar());
        daoAluno = new DaoAluno(conexao.conectar());
        daoAVista = new DaoAVista(conexao.conectar());
        daoAPrazo = new DaoAPrazo(conexao.conectar());

        cursos = daoCurso.listarCursos();

        for (Curso i : cursos) {
            jCbBxCurso.addItem(i.getSigla());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jCbBxTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbBxTurmaActionPerformed
        if (jCbBxTurma.isEnabled()) {
            if (jCbBxTurma.getSelectedItem() != null) {
                jFrmtdTxtFCPF.setEnabled(true);
                jRadBtnAVista.setEnabled(true);
                jRadBtnParcelado.setEnabled(true);
            } else {
                jRadBtnAVista.setSelected(false);
                jRadBtnAVista.setEnabled(false);
                jTxtFAgencia.setEnabled(false);
                jTxtFAgencia.setText("");
                jTxtFNumCheque.setEnabled(false);
                jTxtFNumCheque.setText("");
                jFrmtdTxtFDataPagamento.setEnabled(false);
                jFrmtdTxtFDataPagamento.setText("");

                jRadBtnParcelado.setSelected(false);
                jRadBtnParcelado.setEnabled(false);
                jTxtFQtdeMensalidades.setEnabled(false);
                jTxtFQtdeMensalidades.setText("");
                jTxtFTaxaJuros.setEnabled(false);
                jTxtFTaxaJuros.setText("");
                jFrmtdTxtFDataVencimento.setEnabled(false);
                jFrmtdTxtFDataVencimento.setText("");
            }
        }
    }//GEN-LAST:event_jCbBxTurmaActionPerformed

    private void jRadBtnAVistaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadBtnAVistaStateChanged
        if (jRadBtnAVista.isSelected()) {
            jTxtFAgencia.setEnabled(true);
            jTxtFNumCheque.setEnabled(true);
            jFrmtdTxtFDataPagamento.setEnabled(true);
        } else {
            jTxtFAgencia.setEnabled(false);
            jTxtFAgencia.setText("");
            jTxtFNumCheque.setEnabled(false);
            jTxtFNumCheque.setText("");
            jFrmtdTxtFDataPagamento.setEnabled(false);
            jFrmtdTxtFDataPagamento.setText("");
        }
    }//GEN-LAST:event_jRadBtnAVistaStateChanged

    private void jRadBtnParceladoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadBtnParceladoStateChanged
        if (jRadBtnParcelado.isSelected()) {
            jTxtFQtdeMensalidades.setEnabled(true);
            jTxtFTaxaJuros.setEnabled(true);
            jFrmtdTxtFDataVencimento.setEnabled(true);
        } else {
            jTxtFQtdeMensalidades.setEnabled(false);
            jTxtFQtdeMensalidades.setText("");
            jTxtFTaxaJuros.setEnabled(false);
            jTxtFTaxaJuros.setText("");
            jFrmtdTxtFDataVencimento.setEnabled(false);
            jFrmtdTxtFDataVencimento.setText("");
        }
    }//GEN-LAST:event_jRadBtnParceladoStateChanged

    private void jCbBxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbBxCursoActionPerformed
        curso = cursos.get(jCbBxCurso.getSelectedIndex());
        jTxtFValor.setText(String.valueOf(curso.getValor()));
        jCbBxTurma.removeAllItems();
        turmas = daoTurma.listarTurmasCurso(curso.getSigla());
        for (Turma i : turmas) {
            jCbBxTurma.addItem(i.getSiglaTurma());
        }
    }//GEN-LAST:event_jCbBxCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiEfetuarMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup fprBtnPagamento;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnInserir;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JComboBox<String> jCbBxCurso;
    private javax.swing.JComboBox<String> jCbBxTurma;
    private javax.swing.JFormattedTextField jFrmtdTxtFCPF;
    private javax.swing.JFormattedTextField jFrmtdTxtFDataMatricula;
    private javax.swing.JFormattedTextField jFrmtdTxtFDataPagamento;
    private javax.swing.JFormattedTextField jFrmtdTxtFDataVencimento;
    private javax.swing.JLabel jLblAgencia;
    private javax.swing.JLabel jLblCPF;
    private javax.swing.JLabel jLblCurso;
    private javax.swing.JLabel jLblDataMatricula;
    private javax.swing.JLabel jLblDataPagamento;
    private javax.swing.JLabel jLblDataVencimento;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblNumCheque;
    private javax.swing.JLabel jLblQtdeMensalidades;
    private javax.swing.JLabel jLblTaxaJuros;
    private javax.swing.JLabel jLblTurma;
    private javax.swing.JLabel jLblValor;
    private javax.swing.JPanel jPnlPagamento;
    private javax.swing.JRadioButton jRadBtnAVista;
    private javax.swing.JRadioButton jRadBtnParcelado;
    private javax.swing.JTextField jTxtFAgencia;
    private javax.swing.JTextField jTxtFNome;
    private javax.swing.JTextField jTxtFNumCheque;
    private javax.swing.JTextField jTxtFQtdeMensalidades;
    private javax.swing.JTextField jTxtFTaxaJuros;
    private javax.swing.JTextField jTxtFValor;
    // End of variables declaration//GEN-END:variables
    private DaoMatricula daoMatricula = null;
    private DaoTurma daoTurma = null;
    private DaoCurso daoCurso = null;
    private DaoAluno daoAluno = null;
    private DaoAVista daoAVista = null;
    private DaoAPrazo daoAPrazo = null;
    private Conexao conexao = null;
    private Aluno aluno = null;
    private Curso curso = null;
    private Matricula matricula = null;
    private Turma turma = null;
    private APrazo aprazo = null;
    private AVista avista = null;
    ArrayList<Curso> cursos;
    ArrayList<Turma> turmas;
}
