/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoInstrutor;
import fatec.poo.model.Instrutor;
import fatec.poo.model.Pessoa;
import javax.swing.JOptionPane;

/**
 *
 * @author André Constancio
 * @author Guilherme Sernajoto
 */
public class GuiInstrutor extends javax.swing.JFrame {

    /**
     * Creates new form GuiInstrutor
     */
    public GuiInstrutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblCPF = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jLblSexo = new javax.swing.JLabel();
        jLblEndereco = new javax.swing.JLabel();
        jLblBairro = new javax.swing.JLabel();
        jLblCidade = new javax.swing.JLabel();
        jLblEstado = new javax.swing.JLabel();
        jLblRG = new javax.swing.JLabel();
        jLblFormacao = new javax.swing.JLabel();
        jLblEmail = new javax.swing.JLabel();
        jLblDataNascto = new javax.swing.JLabel();
        jLblEstadoCivil = new javax.swing.JLabel();
        jLblNoEndereco = new javax.swing.JLabel();
        jLblCEP = new javax.swing.JLabel();
        jLblTelRes = new javax.swing.JLabel();
        jLblCel = new javax.swing.JLabel();
        jLblAreaAtuac = new javax.swing.JLabel();
        jFrmtdTxtFCPF = new javax.swing.JFormattedTextField();
        jFrmtdTxtFRG = new javax.swing.JFormattedTextField();
        jFrmtdTxtFDataNascto = new javax.swing.JFormattedTextField();
        jFrmtdTxtFCEP = new javax.swing.JFormattedTextField();
        jFrmtdTxtFTelRes = new javax.swing.JFormattedTextField();
        jFrmtdTxtFCel = new javax.swing.JFormattedTextField();
        jTxtFNome = new javax.swing.JTextField();
        jTxtFEndereco = new javax.swing.JTextField();
        jTxtFBairro = new javax.swing.JTextField();
        jTxtFCidade = new javax.swing.JTextField();
        jTxtFFormacao = new javax.swing.JTextField();
        jTxtFEmail = new javax.swing.JTextField();
        jTxtFNoEndereco = new javax.swing.JTextField();
        jTxtFAreaAtuac = new javax.swing.JTextField();
        jCbBxSexo = new javax.swing.JComboBox<>();
        jCbBxEstado = new javax.swing.JComboBox<>();
        jCbBxEstadoCiv = new javax.swing.JComboBox<>();
        jBtnConsultar = new javax.swing.JButton();
        jBtnInserir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastar Instrutor");
        setPreferredSize(new java.awt.Dimension(650, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLblCPF.setText("CPF");

        jLblNome.setText("Nome");

        jLblSexo.setText("Sexo");

        jLblEndereco.setText("Endereço");

        jLblBairro.setText("Bairro");

        jLblCidade.setText("Cidade");

        jLblEstado.setText("Estado");

        jLblRG.setText("RG");

        jLblFormacao.setText("Formação");

        jLblEmail.setText("Email");

        jLblDataNascto.setText("Data Nascto.");

        jLblEstadoCivil.setText("Estado Civil");

        jLblNoEndereco.setText("Nº");

        jLblCEP.setText("CEP");

        jLblTelRes.setText("Tel. Res.");

        jLblCel.setText("Celular");

        jLblAreaAtuac.setText("Área de Atuação");

        try {
            jFrmtdTxtFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFrmtdTxtFCPFActionPerformed(evt);
            }
        });

        try {
            jFrmtdTxtFRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFRG.setEnabled(false);

        try {
            jFrmtdTxtFDataNascto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFDataNascto.setEnabled(false);

        try {
            jFrmtdTxtFCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFCEP.setEnabled(false);

        try {
            jFrmtdTxtFTelRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFTelRes.setEnabled(false);

        try {
            jFrmtdTxtFCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFrmtdTxtFCel.setEnabled(false);

        jTxtFNome.setEnabled(false);
        jTxtFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFNomeActionPerformed(evt);
            }
        });

        jTxtFEndereco.setEnabled(false);

        jTxtFBairro.setEnabled(false);

        jTxtFCidade.setEnabled(false);

        jTxtFFormacao.setEnabled(false);

        jTxtFEmail.setEnabled(false);

        jTxtFNoEndereco.setEnabled(false);

        jTxtFAreaAtuac.setEnabled(false);

        jCbBxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jCbBxSexo.setEnabled(false);

        jCbBxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jCbBxEstado.setEnabled(false);

        jCbBxEstadoCiv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado", "Solteiro" }));
        jCbBxEstadoCiv.setEnabled(false);

        jBtnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        jBtnConsultar.setText("Consultar");
        jBtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarActionPerformed(evt);
            }
        });

        jBtnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        jBtnInserir.setText("Inserir");
        jBtnInserir.setEnabled(false);
        jBtnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInserirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.setEnabled(false);
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setEnabled(false);
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jBtnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jBtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLblEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblCPF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblNome, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblSexo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblEndereco, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblBairro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblCidade, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblRG, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLblFormacao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFrmtdTxtFRG, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLblEstado)
                                .addGap(53, 53, 53))
                            .addComponent(jTxtFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbBxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFrmtdTxtFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLblAreaAtuac))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jTxtFAreaAtuac, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblDataNascto)
                            .addComponent(jLblEstadoCivil)
                            .addComponent(jLblNoEndereco)
                            .addComponent(jLblCEP)
                            .addComponent(jLblCel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCbBxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLblTelRes)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCbBxEstadoCiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFrmtdTxtFDataNascto)
                            .addComponent(jFrmtdTxtFTelRes)
                            .addComponent(jFrmtdTxtFCEP)
                            .addComponent(jTxtFNoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFrmtdTxtFCel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLblCPF)
                    .addComponent(jFrmtdTxtFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLblNome)
                    .addComponent(jTxtFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblDataNascto)
                    .addComponent(jFrmtdTxtFDataNascto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLblSexo)
                    .addComponent(jCbBxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblEstadoCivil)
                    .addComponent(jCbBxEstadoCiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLblEndereco)
                    .addComponent(jTxtFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNoEndereco)
                    .addComponent(jTxtFNoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLblBairro)
                    .addComponent(jTxtFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCEP)
                    .addComponent(jFrmtdTxtFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLblCidade)
                    .addComponent(jTxtFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblEstado)
                    .addComponent(jCbBxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTelRes)
                    .addComponent(jFrmtdTxtFTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLblRG)
                    .addComponent(jFrmtdTxtFRG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCel)
                    .addComponent(jFrmtdTxtFCel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLblFormacao)
                    .addComponent(jTxtFFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblAreaAtuac)
                    .addComponent(jTxtFAreaAtuac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLblEmail)
                    .addComponent(jTxtFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnConsultar)
                    .addComponent(jBtnInserir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnSair))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Cadastrar Instrutor");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void jTxtFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFNomeActionPerformed

    private void jBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarActionPerformed
    instrutor = null;
       instrutor = daoInstrutor.consultar(jFrmtdTxtFCPF.getText().replaceAll("[.,-]", ""));
       //clearstring = jFrmtdTxtFCPF.getText();
      // clearstring = clearstring.replaceAll("[.,-]", "");
       if (Pessoa.validadarCPF( jFrmtdTxtFCPF.getText().replaceAll("[.,-]", "")) == true){
       if (instrutor == null){
          jBtnConsultar.setEnabled(false);
          jBtnInserir.setEnabled(true);
          jFrmtdTxtFCPF.setEnabled(false);
          
          jTxtFNome.setEnabled(true);
          jCbBxSexo.setEnabled(true);
          jTxtFEndereco.setEnabled(true);
          jTxtFBairro.setEnabled(true);
          jTxtFCidade.setEnabled(true);
          jCbBxEstado.setEnabled(true);
          jFrmtdTxtFRG.setEnabled(true);
          jTxtFFormacao.setEnabled(true);
          jTxtFEmail.setEnabled(true);
          jFrmtdTxtFDataNascto.setEnabled(true);
          jCbBxEstadoCiv.setEnabled(true);
          jTxtFNoEndereco.setEnabled(true);
          jFrmtdTxtFCEP.setEnabled(true);
          jFrmtdTxtFTelRes.setEnabled(true);
          jFrmtdTxtFCel.setEnabled(true);
          jTxtFAreaAtuac.setEnabled(true);
          jTxtFNome.requestFocus();
       }
       else{
       jTxtFNome.setText(instrutor.getNome());
       jCbBxSexo.setSelectedItem(instrutor.getSexo());
       jTxtFEndereco.setText(instrutor.getEndereco());
       jTxtFBairro.setText(instrutor.getBairro());
       jTxtFCidade.setText(instrutor.getCidade());
       jCbBxEstado.setSelectedItem(instrutor.getEstado());
       jFrmtdTxtFRG.setText(instrutor.getRg());
       jTxtFFormacao.setText(instrutor.getFormacao());
       jTxtFEmail.setText(instrutor.getEmail());
       jFrmtdTxtFDataNascto.setText(instrutor.getDataNasc());
       jCbBxEstadoCiv.setSelectedItem(instrutor.getEstadoCivil());
       jTxtFNoEndereco.setText(String.valueOf(instrutor.getNumero()));
       jFrmtdTxtFCEP.setText(String.valueOf(instrutor.getCep()));
       jFrmtdTxtFTelRes.setText(String.valueOf(instrutor.getTelefone()));
       jFrmtdTxtFCel.setText(String.valueOf(instrutor.getCelular()));
       jTxtFAreaAtuac.setText(instrutor.getAreaAtuacao());
              
       jBtnConsultar.setEnabled(false);
       jBtnAlterar.setEnabled(true);
       jBtnExcluir.setEnabled(true);
           
            jTxtFNome.setEnabled(true);
          jCbBxSexo.setEnabled(true);
          jTxtFEndereco.setEnabled(true);
          jCbBxEstado.setEnabled(true);
          jTxtFBairro.setEnabled(true);
          jTxtFCidade.setEnabled(true);
          jFrmtdTxtFRG.setEnabled(true);
          jTxtFFormacao.setEnabled(true);
          jTxtFEmail.setEnabled(true);
          jFrmtdTxtFDataNascto.setEnabled(true);
          jCbBxEstadoCiv.setEnabled(true);
          jTxtFNoEndereco.setEnabled(true);
          jFrmtdTxtFCEP.setEnabled(true);
          jFrmtdTxtFTelRes.setEnabled(true);
          jFrmtdTxtFCel.setEnabled(true);
          jTxtFAreaAtuac.setEnabled(true);
          jTxtFNome.requestFocus();
          }         
    }//GEN-LAST:event_jBtnConsultarActionPerformed
       else{
           JOptionPane.showMessageDialog(null,"O CPF informado e invalido");
       }
   }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           conexao = new Conexao("POO", "contaORACLE$2");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        daoInstrutor= new DaoInstrutor(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void jFrmtdTxtFCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFrmtdTxtFCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrmtdTxtFCPFActionPerformed

    private void jBtnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInserirActionPerformed
        instrutor = new Instrutor((jTxtFNome.getText()), jFrmtdTxtFCPF.getText().replaceAll("[.,-]", ""));
        
        instrutor.setSexo(jCbBxSexo.getSelectedItem().toString());
        instrutor.setEstado(jCbBxEstado.getSelectedItem().toString());
        instrutor.setEstadoCivil(jCbBxEstadoCiv.getSelectedItem().toString());
        
        instrutor.setRg(jFrmtdTxtFRG.getText().replaceAll("[.,-]", ""));
        instrutor.setDataNasc(jFrmtdTxtFDataNascto.getText());
        instrutor.setTelefone(jFrmtdTxtFTelRes.getText().replaceAll("[(,),-]", ""));
        instrutor.setCelular(jFrmtdTxtFCel.getText().replaceAll("[(,),-]", ""));
        instrutor.setCep(jFrmtdTxtFCEP.getText().replaceAll("-", ""));
        
        instrutor.setEndereco(jTxtFEndereco.getText());
        instrutor.setBairro(jTxtFBairro.getText());
        instrutor.setCidade(jTxtFCidade.getText());
         instrutor.setNumero(Integer.parseInt(jTxtFNoEndereco.getText()));
        instrutor.setFormacao(jTxtFFormacao.getText());
        instrutor.setAreaAtuacao(jTxtFAreaAtuac.getText());
        instrutor.setEmail(jTxtFEmail.getText());
        
        daoInstrutor.inserir(instrutor);
        
         jBtnConsultar.setEnabled(true);
         jBtnInserir.setEnabled(false);
         jBtnAlterar.setEnabled(false);
         jBtnExcluir.setEnabled(false);
        
       jFrmtdTxtFCPF.setText("");
        jTxtFNome.setText("");
       jCbBxSexo.setSelectedItem("M");
       jTxtFEndereco.setText("");
       jTxtFBairro.setText("");
       jTxtFCidade.setText("");
       jCbBxEstado.setSelectedItem("AC");
       jFrmtdTxtFRG.setText("");
       jTxtFFormacao.setText("");
       jTxtFEmail.setText("");
       jFrmtdTxtFDataNascto.setText("");
       jCbBxEstadoCiv.setSelectedItem("Casado");
       jTxtFNoEndereco.setText("");
       jFrmtdTxtFCEP.setText("");
       jFrmtdTxtFTelRes.setText("");
       jFrmtdTxtFCel.setText("");
       jTxtFAreaAtuac.setText("");
       
        jFrmtdTxtFCPF.setEnabled(true);
        jTxtFNome.setEnabled(false);
       jCbBxSexo.setEnabled(false);
       jTxtFEndereco.setEnabled(false);
       jTxtFBairro.setEnabled(false);
       jTxtFCidade.setEnabled(false);
       jCbBxEstado.setEnabled(false);
       jFrmtdTxtFRG.setEnabled(false);
       jTxtFFormacao.setEnabled(false);
       jTxtFEmail.setEnabled(false);
       jFrmtdTxtFDataNascto.setEnabled(false);
       jCbBxEstadoCiv.setEnabled(false);
       jTxtFNoEndereco.setEnabled(false);
       jFrmtdTxtFCEP.setEnabled(false);
       jFrmtdTxtFTelRes.setEnabled(false);
       jFrmtdTxtFCel.setEnabled(false);
       jTxtFAreaAtuac.setEnabled(false);
       
       jTxtFNome.requestFocus();
    }//GEN-LAST:event_jBtnInserirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
       
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?")== 0){
            
            instrutor.setSexo(jCbBxSexo.getSelectedItem().toString());
            instrutor.setEstado(jCbBxEstado.getSelectedItem().toString());
            instrutor.setEstadoCivil(jCbBxEstadoCiv.getSelectedItem().toString());
            
              instrutor.setRg(jFrmtdTxtFRG.getText().replaceAll("[.,-]", ""));
        instrutor.setDataNasc(jFrmtdTxtFDataNascto.getText());
        instrutor.setTelefone(jFrmtdTxtFTelRes.getText().replaceAll("[(,),-]", ""));
        instrutor.setCelular(jFrmtdTxtFCel.getText().replaceAll("[(,),-]", ""));
        instrutor.setCep(jFrmtdTxtFCEP.getText().replaceAll("-", ""));
            
            instrutor.setEndereco(jTxtFEndereco.getText());
            instrutor.setBairro(jTxtFBairro.getText());
            instrutor.setCidade(jTxtFCidade.getText());
            instrutor.setNumero(Integer.parseInt(jTxtFNoEndereco.getText()));
            instrutor.setFormacao(jTxtFFormacao.getText());
            instrutor.setAreaAtuacao(jTxtFAreaAtuac.getText());
            instrutor.setEmail(jTxtFEmail.getText());
            
           daoInstrutor.alterar(instrutor);
        }
        
            jBtnConsultar.setEnabled(true);
            jBtnInserir.setEnabled(false);
            jBtnAlterar.setEnabled(false);
            jBtnExcluir.setEnabled(false);        
        
           jFrmtdTxtFCPF.setText("");
           jTxtFNome.setText("");
           jCbBxSexo.setSelectedItem("M");
           jTxtFEndereco.setText("");
           jTxtFBairro.setText("");
           jTxtFCidade.setText("");
           jCbBxEstado.setSelectedItem("AC");
           jFrmtdTxtFRG.setText("");
           jTxtFFormacao.setText("");
           jTxtFEmail.setText("");
           jFrmtdTxtFDataNascto.setText("");
           jCbBxEstadoCiv.setSelectedItem("Casado");
           jTxtFNoEndereco.setText("");
           jFrmtdTxtFCEP.setText("");
           jFrmtdTxtFTelRes.setText("");
           jFrmtdTxtFCel.setText("");
           jTxtFAreaAtuac.setText("");
           
           jFrmtdTxtFCPF.setEnabled(true);
           jTxtFNome.setEnabled(false);
           jCbBxSexo.setEnabled(false);
           jTxtFEndereco.setEnabled(false);
           jTxtFBairro.setEnabled(false);
           jTxtFCidade.setEnabled(false);
           jCbBxEstado.setEnabled(false);
           jFrmtdTxtFRG.setEnabled(false);
           jTxtFFormacao.setEnabled(false);
           jTxtFEmail.setEnabled(false);
           jFrmtdTxtFDataNascto.setEnabled(false);
           jCbBxEstadoCiv.setEnabled(false);
           jTxtFNoEndereco.setEnabled(false);
           jFrmtdTxtFCEP.setEnabled(false);
           jFrmtdTxtFTelRes.setEnabled(false);
           jFrmtdTxtFCel.setEnabled(false);
           jTxtFAreaAtuac.setEnabled(false);
           
           jTxtFNome.requestFocus();
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
 if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0){
            daoInstrutor.excluir(instrutor);
        
           jFrmtdTxtFCPF.setText("");
            jTxtFNome.setText("");
           jCbBxSexo.setSelectedItem("M");
           jTxtFEndereco.setText("");
           jTxtFBairro.setText("");
           jTxtFCidade.setText("");
           jCbBxEstado.setSelectedItem("AC");
           jFrmtdTxtFRG.setText("");
           jTxtFFormacao.setText("");
           jTxtFEmail.setText("");
           jFrmtdTxtFDataNascto.setText("");
           jCbBxEstadoCiv.setSelectedItem("Casado");
           jTxtFNoEndereco.setText("");
           jFrmtdTxtFCEP.setText("");
           jFrmtdTxtFTelRes.setText("");
           jFrmtdTxtFCel.setText("");
           jTxtFAreaAtuac.setText("");
           
           jBtnConsultar.setEnabled(true);
           jBtnInserir.setEnabled(false);
           jBtnAlterar.setEnabled(false);
           jBtnExcluir.setEnabled(false);
           
           jFrmtdTxtFCPF.setEnabled(true);
           jTxtFNome.setEnabled(false);
           jCbBxSexo.setEnabled(false);
           jTxtFEndereco.setEnabled(false);
           jTxtFBairro.setEnabled(false);
           jTxtFCidade.setEnabled(false);
           jCbBxEstado.setEnabled(false);
           jFrmtdTxtFRG.setEnabled(false);
           jTxtFFormacao.setEnabled(false);
           jTxtFEmail.setEnabled(false);
           jFrmtdTxtFDataNascto.setEnabled(false);
           jCbBxEstadoCiv.setEnabled(false);
           jTxtFNoEndereco.setEnabled(false);
           jFrmtdTxtFCEP.setEnabled(false);
           jFrmtdTxtFTelRes.setEnabled(false);
           jFrmtdTxtFCel.setEnabled(false);
           jTxtFAreaAtuac.setEnabled(false);
        }        
    }//GEN-LAST:event_jBtnExcluirActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiInstrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnInserir;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JComboBox<String> jCbBxEstado;
    private javax.swing.JComboBox<String> jCbBxEstadoCiv;
    private javax.swing.JComboBox<String> jCbBxSexo;
    private javax.swing.JFormattedTextField jFrmtdTxtFCEP;
    private javax.swing.JFormattedTextField jFrmtdTxtFCPF;
    private javax.swing.JFormattedTextField jFrmtdTxtFCel;
    private javax.swing.JFormattedTextField jFrmtdTxtFDataNascto;
    private javax.swing.JFormattedTextField jFrmtdTxtFRG;
    private javax.swing.JFormattedTextField jFrmtdTxtFTelRes;
    private javax.swing.JLabel jLblAreaAtuac;
    private javax.swing.JLabel jLblBairro;
    private javax.swing.JLabel jLblCEP;
    private javax.swing.JLabel jLblCPF;
    private javax.swing.JLabel jLblCel;
    private javax.swing.JLabel jLblCidade;
    private javax.swing.JLabel jLblDataNascto;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblEndereco;
    private javax.swing.JLabel jLblEstado;
    private javax.swing.JLabel jLblEstadoCivil;
    private javax.swing.JLabel jLblFormacao;
    private javax.swing.JLabel jLblNoEndereco;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblRG;
    private javax.swing.JLabel jLblSexo;
    private javax.swing.JLabel jLblTelRes;
    private javax.swing.JTextField jTxtFAreaAtuac;
    private javax.swing.JTextField jTxtFBairro;
    private javax.swing.JTextField jTxtFCidade;
    private javax.swing.JTextField jTxtFEmail;
    private javax.swing.JTextField jTxtFEndereco;
    private javax.swing.JTextField jTxtFFormacao;
    private javax.swing.JTextField jTxtFNoEndereco;
    private javax.swing.JTextField jTxtFNome;
    // End of variables declaration//GEN-END:variables
private DaoInstrutor daoInstrutor = null;
private Instrutor instrutor = null;
private Conexao conexao = null;
private String clearstring = "";
}
